[pytest]
addopts = -p no:cacheprovider
norecursedirs = pytest-cache-files-* .git .venv node_modules
asyncio_mode = auto
asyncio_default_fixture_loop_scope = function
filterwarnings =
    ignore::DeprecationWarning:tortoise.*:
    ignore:.*Tortoise connection 'default' was created on a different event loop.*
